#!/bin/bash

# Install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor

brew update
brew install caskroom/cask/brew-cask

brew install rbenv ruby-build
brew install curl
brew install cloc
brew install 

# Node Version Manager
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

brew install macvim --with-override-system-vim --lua

# Brew Cask
brew cask install finicky

